[target.armv7-unknown-linux-musleabi]
pre-build = ["dpkg --add-architecture armel && apt-get update && apt-get install --assume-yes libsqlite3-dev:armel"]

[target.armv7-unknown-linux-musleabihf]
pre-build = ["dpkg --add-architecture armhf && apt-get update && apt-get install --assume-yes libsqlite3-dev:armhf"]

[target.aarch64-unknown-linux-musl]
pre-build = ["dpkg --add-architecture arm64 && apt-get update && apt-get install --assume-yes libsqlite3-dev:arm64"]

[target.x86_64-unknown-linux-musl]
pre-build = ["dpkg --add-architecture amd64 && apt-get update && apt-get install --assume-yes libsqlite3-dev:amd64"]


