[target.armv7-unknown-linux-musleabi]
pre-build = ["dpkg --add-architecture armhf && apt-get update && apt-get install --assume-yes libsqlite3-dev:armhf"]

[target.armv7-unknown-linux-musleabihf]
pre-build = ["dpkg --add-architecture armhf && apt-get update && apt-get install --assume-yes libsqlite3-dev:armhf"]

