# SPDX-FileCopyrightText: 2023 Dom Rodriguez
#
# SPDX-License-Identifier: MIT

[toolchain]
channel = "stable"
components = ["rust-src", "rustfmt", "llvm-tools-preview"]
targets = [
    "x86_64-unknown-linux-musl",
    "armv7-unknown-linux-musleabi",
    "armv7-unknown-linux-musleabihf",
    "aarch64-unknown-linux-musl"
]
