name: CI workflow

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Update aptitude
      run: sudo apt-get update
    - name: Install libdbus-1-dev
      run: sudo apt-get install -y libdbus-1-dev
    - name: Build scrobblers
      run: cargo build --verbose
    - name: Run tests for scrobblers
      run: cargo test --verbose
