name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the `scrob` project! Please make sure to read the Code of Conduct in the meantime, and we will respond when we can."
        pr-message: "Welcome to the `scrob` project! Please make sure to read the Code of Conduct in the meantime, and we will respond when we can. Thank you for your contribution!"
